FROM python:3.8-slim-bullseye AS base

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

ENV HOME=/app
RUN mkdir $HOME
WORKDIR $HOME

COPY requirements.dev.txt $HOME/requirements.txt


RUN apt-get update && \
  apt-get install -y gcc netcat 
RUN apt-get install -y \
  gcc \
  default-libmysqlclient-dev \
  pkg-config \
  curl


RUN mkdir $HOME/public
RUN mkdir $HOME/public/media
RUN mkdir $HOME/public/static
RUN mkdir $HOME/mlrec
RUN mkdir $HOME/mlrec/models_data

RUN pip install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt && \
  apt-get remove -y \
  gcc \
  pkg-config && \
  rm -rf /var/lib/apt/lists/*

COPY . .

COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' entrypoint.sh
RUN chmod +x entrypoint.sh


ENTRYPOINT ["sh", "./entrypoint.sh"]